# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_pinver.ui',
# licensing of 'dialog_pinver.ui' applies.
#
# Created: Wed Dec 11 16:04:21 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from HVmodules.NModule import *

class Ui_dialogpinver(object):
    def setupUi(self, dialogpinver):
        dialogpinver.setObjectName("dialogpinver")
        dialogpinver.resize(332, 340)
        self.layoutWidget = QtWidgets.QWidget(dialogpinver)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 311, 326))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_pinver = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_pinver.setObjectName("groupBox_pinver")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_pinver)
        self.formLayout.setObjectName("formLayout")
        self.label_iter = QtWidgets.QLabel(self.groupBox_pinver)
        self.label_iter.setObjectName("label_iter")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_iter)
        self.spinBox_iter = QtWidgets.QSpinBox(self.groupBox_pinver)
        self.spinBox_iter.setMinimum(1)
        self.spinBox_iter.setMaximum(10000)
        self.spinBox_iter.setObjectName("spinBox_iter")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_iter)
        self.label_parts = QtWidgets.QLabel(self.groupBox_pinver)
        self.label_parts.setObjectName("label_parts")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_parts)
        self.spinBox_parts = QtWidgets.QSpinBox(self.groupBox_pinver)
        self.spinBox_parts.setMinimum(1)
        self.spinBox_parts.setMaximum(10000)
        self.spinBox_parts.setObjectName("spinBox_parts")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_parts)
        self.label_wini = QtWidgets.QLabel(self.groupBox_pinver)
        self.label_wini.setObjectName("label_wini")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_wini)
        self.doubleSpinBox_wini = QtWidgets.QDoubleSpinBox(self.groupBox_pinver)
        self.doubleSpinBox_wini.setDecimals(5)
        self.doubleSpinBox_wini.setMaximum(3.0)
        self.doubleSpinBox_wini.setSingleStep(0.01)
        self.doubleSpinBox_wini.setObjectName("doubleSpinBox_wini")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_wini)
        self.label_wa = QtWidgets.QLabel(self.groupBox_pinver)
        self.label_wa.setObjectName("label_wa")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_wa)
        self.doubleSpinBox_wa = QtWidgets.QDoubleSpinBox(self.groupBox_pinver)
        self.doubleSpinBox_wa.setDecimals(5)
        self.doubleSpinBox_wa.setMaximum(1.0)
        self.doubleSpinBox_wa.setSingleStep(0.1)
        self.doubleSpinBox_wa.setObjectName("doubleSpinBox_wa")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_wa)
        self.label_c1 = QtWidgets.QLabel(self.groupBox_pinver)
        self.label_c1.setObjectName("label_c1")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_c1)
        self.doubleSpinBox_c1 = QtWidgets.QDoubleSpinBox(self.groupBox_pinver)
        self.doubleSpinBox_c1.setDecimals(5)
        self.doubleSpinBox_c1.setMaximum(2.0)
        self.doubleSpinBox_c1.setSingleStep(0.5)
        self.doubleSpinBox_c1.setObjectName("doubleSpinBox_c1")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_c1)
        self.label_c2 = QtWidgets.QLabel(self.groupBox_pinver)
        self.label_c2.setObjectName("label_c2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_c2)
        self.doubleSpinBox_c2 = QtWidgets.QDoubleSpinBox(self.groupBox_pinver)
        self.doubleSpinBox_c2.setDecimals(5)
        self.doubleSpinBox_c2.setMaximum(2.0)
        self.doubleSpinBox_c2.setSingleStep(0.5)
        self.doubleSpinBox_c2.setObjectName("doubleSpinBox_c2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_c2)
        self.label_velmax = QtWidgets.QLabel(self.groupBox_pinver)
        self.label_velmax.setObjectName("label_velmax")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_velmax)
        self.doubleSpinBox_velmax = QtWidgets.QDoubleSpinBox(self.groupBox_pinver)
        self.doubleSpinBox_velmax.setDecimals(5)
        self.doubleSpinBox_velmax.setMaximum(1.0)
        self.doubleSpinBox_velmax.setSingleStep(0.5)
        self.doubleSpinBox_velmax.setObjectName("doubleSpinBox_velmax")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_velmax)
        self.label_vpgrad = QtWidgets.QLabel(self.groupBox_pinver)
        self.label_vpgrad.setObjectName("label_vpgrad")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_vpgrad)
        self.label_vsgrad = QtWidgets.QLabel(self.groupBox_pinver)
        self.label_vsgrad.setObjectName("label_vsgrad")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_vsgrad)
        self.label_dengrad = QtWidgets.QLabel(self.groupBox_pinver)
        self.label_dengrad.setObjectName("label_dengrad")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_dengrad)
        self.doubleSpinBox_vpgrad = QtWidgets.QDoubleSpinBox(self.groupBox_pinver)
        self.doubleSpinBox_vpgrad.setDecimals(5)
        self.doubleSpinBox_vpgrad.setMaximum(1.0)
        self.doubleSpinBox_vpgrad.setSingleStep(0.001)
        self.doubleSpinBox_vpgrad.setProperty("value", 0.01)
        self.doubleSpinBox_vpgrad.setObjectName("doubleSpinBox_vpgrad")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_vpgrad)
        self.doubleSpinBox_vsgrad = QtWidgets.QDoubleSpinBox(self.groupBox_pinver)
        self.doubleSpinBox_vsgrad.setDecimals(5)
        self.doubleSpinBox_vsgrad.setMaximum(1.0)
        self.doubleSpinBox_vsgrad.setSingleStep(0.001)
        self.doubleSpinBox_vsgrad.setProperty("value", 0.009)
        self.doubleSpinBox_vsgrad.setObjectName("doubleSpinBox_vsgrad")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_vsgrad)
        self.doubleSpinBox_dengrad = QtWidgets.QDoubleSpinBox(self.groupBox_pinver)
        self.doubleSpinBox_dengrad.setDecimals(5)
        self.doubleSpinBox_dengrad.setMaximum(1.0)
        self.doubleSpinBox_dengrad.setSingleStep(0.001)
        self.doubleSpinBox_dengrad.setProperty("value", 0.02)
        self.doubleSpinBox_dengrad.setObjectName("doubleSpinBox_dengrad")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_dengrad)
        self.verticalLayout.addWidget(self.groupBox_pinver)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_info = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_info.setObjectName("pushButton_info")
        self.horizontalLayout.addWidget(self.pushButton_info)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(dialogpinver)
        self.buttonBox.accepted.connect(dialogpinver.accept)
        self.buttonBox.rejected.connect(dialogpinver.reject)
        QtCore.QMetaObject.connectSlotsByName(dialogpinver)
        self.default()

    def default(self):
        self.spinBox_iter.setValue(50.0)
        self.spinBox_parts.setValue(15)
        self.doubleSpinBox_wini.setValue(2)
        self.doubleSpinBox_wa.setValue(0.8)
        self.doubleSpinBox_velmax.setValue(0.5)
        self.doubleSpinBox_c1.setValue(2.0)
        self.doubleSpinBox_c2.setValue(2.0)
        self.doubleSpinBox_vpgrad.setValue(0.0001)
        self.doubleSpinBox_vsgrad.setValue(0.009)
        self.doubleSpinBox_dengrad.setValue(0.02)

    def retranslateUi(self, dialogpinver):
        _translate = QtCore.QCoreApplication.translate
        dialogpinver.setWindowTitle(_translate("dialogpinver", "Parámetros de inversión"))
        self.groupBox_pinver.setTitle(_translate("dialogpinver", "PSO"))
        self.label_iter.setText(_translate("dialogpinver", "Iteraciones:"))
        self.label_parts.setText(_translate("dialogpinver", "Particulas:"))
        self.label_wini.setText(_translate("dialogpinver", "Factor de inercia inicial:"))
        self.label_wa.setText(_translate("dialogpinver", "Amortiguamiento:"))
        self.label_c1.setText(_translate("dialogpinver", "Coeficiente cognitivo:"))
        self.label_c2.setText(_translate("dialogpinver", "Coeficiente social:"))
        self.label_velmax.setText(_translate("dialogpinver", "Factor de velocidad:"))
        self.label_vpgrad.setText(_translate("dialogpinver", "Gradiente de Vp:"))
        self.label_vsgrad.setText(_translate("dialogpinver", "Gradiente de Vs:"))
        self.label_dengrad.setText(_translate("dialogpinver", "Gradiente de densidad:"))
        self.pushButton_info.setText(_translate("dialogpinver", "Info"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialogpinver = QtWidgets.QDialog()
    ui = Ui_dialogpinver()
    ui.setupUi(dialogpinver)
    dialogpinver.show()
    sys.exit(app.exec_())

