from HVmodules.NModule import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        #MainWindow.resize(1032, 861)
        MainWindow.resize(1432, 861)
        font = QtGui.QFont("MS Shell Dlg 2", 10.5)
        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.centralwidget.setLayout(self.verticalLayout)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")


        self.treeWidget_project = QtWidgets.QTreeWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_project.sizePolicy().hasHeightForWidth())
        self.treeWidget_project.setSizePolicy(sizePolicy)
        self.treeWidget_project.setMinimumSize(QtCore.QSize(200, 0))
        self.treeWidget_project.setMaximumSize(QtCore.QSize(400, 16777215))
        self.treeWidget_project.setObjectName("treeWidget_project")
        self.horizontalLayout.addWidget(self.treeWidget_project)
        self.tabWidget = QtWidgets.QTabWidget()
        self.tabWidget.setObjectName("tabWidget")
        self.tab_procesamiento = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_procesamiento.sizePolicy().hasHeightForWidth())
        self.tab_procesamiento.setSizePolicy(sizePolicy)
        self.tab_procesamiento.setObjectName("tab_procesamiento")
        layoutProcesamiento=QtWidgets.QGridLayout()
        self.tab_procesamiento.setLayout(layoutProcesamiento)
        self.mdiArea = QtWidgets.QMdiArea()
        layoutProcesamiento.addWidget(self.mdiArea,0,0,2,2)
        self.mdiArea.setGeometry(QtCore.QRect(0, 0, 1650, 1000))
        self.mdiArea.setObjectName("mdiArea")
        self.tabWidget.addTab(self.tab_procesamiento, "")
        self.tab_inversion = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_inversion.sizePolicy().hasHeightForWidth())
        self.tab_inversion.setSizePolicy(sizePolicy)
        self.tab_inversion.setObjectName("tab_inversion")
        layoutInversion = QtWidgets.QGridLayout()
        self.tab_inversion.setLayout(layoutInversion)
        self.mdiArea_INV = QtWidgets.QMdiArea()
        layoutInversion.addWidget(self.mdiArea_INV)
        self.mdiArea_INV.setGeometry(QtCore.QRect(0, 0, 1650, 1000))
        self.mdiArea_INV.setObjectName("mdiArea_INV")
        self.tabWidget.addTab(self.tab_inversion, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.menubar = QtWidgets.QMenuBar()
        MainWindow.setMenuBar(self.menubar)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1032, 22))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuAbrir = QtWidgets.QMenu(self.menuArchivo)
        self.menuAbrir.setObjectName("menuAbrir")
        self.menuEditar = QtWidgets.QMenu(self.menubar)
        self.menuEditar.setObjectName("menuEditar")
        self.menuH_V = QtWidgets.QMenu(self.menubar)
        self.menuH_V.setObjectName("menuH_V")
        self.statusbar = QtWidgets.QStatusBar()
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbrir_V_A = QtWidgets.QAction()
        self.actionAbrir_V_A.setObjectName("actionAbrir_V_A")
        self.actionAbrir_proyecto_de_V_A = QtWidgets.QAction()
        self.actionAbrir_proyecto_de_V_A.setObjectName("actionAbrir_proyecto_de_V_A")
        self.actionAbrir_HVSR = QtWidgets.QAction()
        self.actionAbrir_HVSR.setObjectName("actionAbrir_HVSR")
        self.actionABrir_proyecto_de_HVSR = QtWidgets.QAction()
        self.actionABrir_proyecto_de_HVSR.setObjectName("actionABrir_proyecto_de_HVSR")

        self.actionAbrirProyectoTW = QtWidgets.QAction()
        self.actionAbrirProyectoTW.setObjectName("actionAbrirProyectoTW")

        self.actionGuardarproyecto = QtWidgets.QAction()
        self.actionGuardarproyecto.setObjectName("actionGuardarproyecto")
        self.actionGuardar_como = QtWidgets.QAction()
        self.actionGuardar_como.setObjectName("actionGuardar_como")
        self.actionCerrar = QtWidgets.QAction()
        self.actionCerrar.setObjectName("actionCerrar")
        self.actionDeshacer = QtWidgets.QAction()
        self.actionDeshacer.setObjectName("actionDeshacer")
        self.actionRehacer = QtWidgets.QAction()
        self.actionRehacer.setObjectName("actionRehacer")
        self.actionParamsVents = QtWidgets.QAction()
        self.actionParamsVents.setObjectName("actionParamsVents")
        self.menuAbrir.addAction(self.actionAbrir_V_A)
        self.menuAbrir.addSeparator()
        self.menuAbrir.addSeparator()
        self.menuAbrir.addAction(self.actionAbrir_HVSR)
        self.menuAbrir.addSeparator()
        self.menuAbrir.addSeparator()
        self.menuAbrir.addAction(self.actionAbrirProyectoTW)
        self.menuArchivo.addAction(self.menuAbrir.menuAction())
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionGuardarproyecto)
        self.menuArchivo.addAction(self.actionGuardar_como)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionCerrar)
        self.menuEditar.addSeparator()
        self.menuEditar.addAction(self.actionDeshacer)
        self.menuEditar.addSeparator()
        self.menuEditar.addAction(self.actionRehacer)
        self.menuH_V.addAction(self.actionParamsVents)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuEditar.menuAction())
        self.menubar.addAction(self.menuH_V.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionCerrar.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Procesamiento e Inversión de HVNR"))
        self.treeWidget_project.headerItem().setText(0, _translate("MainWindow", "Proyectos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_procesamiento), _translate("MainWindow", "Procesamiento"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_inversion), _translate("MainWindow", "Inversión"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuAbrir.setTitle(_translate("MainWindow", "Abrir "))
        self.menuEditar.setTitle(_translate("MainWindow", "Editar"))
        self.menuH_V.setTitle(_translate("MainWindow", "H/V"))
        self.actionAbrir_V_A.setText(_translate("MainWindow", "Abrir archivos de V.A."))
        self.actionAbrir_proyecto_de_V_A.setText(_translate("MainWindow", "Abrir archivos de V.A."))
        self.actionAbrir_HVSR.setText(_translate("MainWindow", "Abrir archivos de HV"))
        self.actionABrir_proyecto_de_HVSR.setText(_translate("MainWindow", "Abrir archivos de H/V"))
        self.actionGuardarproyecto.setText(_translate("MainWindow", "Guardar proyecto"))
        self.actionAbrirProyectoTW.setText(_translate("MainWindow", "Abrir proyecto TerraWare H/V"))
        self.actionGuardar_como.setText(_translate("MainWindow", "Guardar como"))
        self.actionCerrar.setText(_translate("MainWindow", "Cerrar"))
        self.actionDeshacer.setText(_translate("MainWindow", "Deshacer"))
        self.actionRehacer.setText(_translate("MainWindow", "Rehacer"))
        self.actionParamsVents.setText(_translate("MainWindow", "Parámetros de selección de ventanas"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())